'use server';

/**
 * @fileOverview Refines an image prompt using AI to produce higher quality and more relevant results.
 *
 * - refineImagePrompt - A function that refines the image prompt.
 * - RefineImagePromptInput - The input type for the refineImagePrompt function.
 * - RefineImagePromptOutput - The return type for the refineImagePrompt function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const RefineImagePromptInputSchema = z.object({
  prompt: z.string().describe('The original image prompt provided by the user.'),
});
export type RefineImagePromptInput = z.infer<typeof RefineImagePromptInputSchema>;

const RefineImagePromptOutputSchema = z.object({
  refinedPrompt: z.string().describe('The refined image prompt generated by the AI.'),
});
export type RefineImagePromptOutput = z.infer<typeof RefineImagePromptOutputSchema>;

export async function refineImagePrompt(input: RefineImagePromptInput): Promise<RefineImagePromptOutput> {
  return refineImagePromptFlow(input);
}

const refineImagePromptPrompt = ai.definePrompt({
  name: 'refineImagePromptPrompt',
  input: {schema: RefineImagePromptInputSchema},
  output: {schema: RefineImagePromptOutputSchema},
  prompt: `You are an AI image prompt refiner. Your job is to take a user-provided image prompt and refine it to produce higher quality and more relevant results. The refined prompt should be more descriptive and specific than the original prompt.

Original Prompt: {{{prompt}}}

Refined Prompt:`, // Ensure the AI only outputs the refined prompt
});

const refineImagePromptFlow = ai.defineFlow(
  {
    name: 'refineImagePromptFlow',
    inputSchema: RefineImagePromptInputSchema,
    outputSchema: RefineImagePromptOutputSchema,
  },
  async input => {
    const {output} = await refineImagePromptPrompt(input);
    return output!;
  }
);
